version: "3.8"
services:
    web-api:
        container_name: web-api
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        working_dir: /app
        volumes:
            - ./:/app
        ports:
            - 9090:9090
